[package]
name = "pi_data_receiver"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = "0.26.0"
serialport = "4.0.0"
socket2 = "0.4.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.8"